use serde::{Deserialize, Serialize};
use sqlx::FromRow;
use uuid::Uuid;

use crate::errors::DatabaseError;

/// Which aggregate a [`SearchResult`] points at. Mirrors the
/// `entity_type` value written into `search_index` by the triggers in
/// `migrations/0005_search_fts.sql` (`'workspace'` / `'file'`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SearchEntityType {
    Workspace,
    File,
}

impl SearchEntityType {
    pub fn as_str(&self) -> &'static str {
        match self {
            SearchEntityType::Workspace => "workspace",
            SearchEntityType::File => "file",
        }
    }
}

impl std::str::FromStr for SearchEntityType {
    type Err = DatabaseError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "workspace" => Ok(SearchEntityType::Workspace),
            "file" => Ok(SearchEntityType::File),
            other => Err(DatabaseError::InvalidInput(format!(
                "unknown search entity type '{other}'"
            ))),
        }
    }
}

/// One hit from [`crate::repositories::search_repository::SearchRepository::search`]
/// (blueprint §4.2, §9 — Hybrid Search). `snippet` is a BM25-ranked,
/// match-highlighted excerpt generated by SQLite FTS5's `snippet()`
/// function, not a fixed substring — see the repository for exact
/// highlighting markers.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SearchResult {
    pub entity_type: SearchEntityType,
    pub entity_id: Uuid,
    pub workspace_id: Uuid,
    pub title: String,
    pub snippet: String,
    /// Lower is a better match — the raw FTS5 `bm25()` rank, exposed so
    /// the frontend can show a relative confidence indicator if it wants
    /// to, without the backend having to normalize it into a 0-100 score
    /// that would just be re-derived from this anyway.
    pub rank: f64,
}

/// Raw shape of a `search_index` row joined with its match rank —
/// see [`crate::models::workspace::WorkspaceRow`] for why enum columns
/// are decoded as `String` first.
#[derive(Debug, FromRow)]
pub(crate) struct SearchResultRow {
    pub entity_type: String,
    pub entity_id: Uuid,
    pub workspace_id: Uuid,
    pub title: String,
    pub snippet: String,
    pub rank: f64,
}

impl TryFrom<SearchResultRow> for SearchResult {
    type Error = DatabaseError;

    fn try_from(row: SearchResultRow) -> Result<Self, Self::Error> {
        Ok(SearchResult {
            entity_type: row.entity_type.parse()?,
            entity_id: row.entity_id,
            workspace_id: row.workspace_id,
            title: row.title,
            snippet: row.snippet,
            rank: row.rank,
        })
    }
}

/// A file re-indexed for search once the (Phase 5) ML layer or a content
/// scanner has extracted body text worth searching, beyond just its
/// path. Not populated by anything in Phase 4 — `files.content_hash` and
/// this stay `None`/absent until a content-reading feature exists — but
/// modeled now (mirroring the `ml_metadata` table's "created now, filled
/// later" pattern from `migrations/0001_initial_schema.sql`) so
/// `SearchRepository::reindex_file` has a stable signature to extend.
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ReindexFileBody {
    pub file_id: Uuid,
    pub body: String,
}

/// A saved search query.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
#[serde(rename_all = "camelCase")]
pub struct SavedSearch {
    pub id: Uuid,
    pub query: String,
    pub created_at: chrono::DateTime<chrono::Utc>,
}

/// Summary statistics for search indexing.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SearchStats {
    pub total_files: i64,
    pub total_workspaces: i64,
    pub last_indexed: Option<chrono::DateTime<chrono::Utc>>,
}

// A single indexed timestamp bookkeeping record — unused by Phase 4's
// synchronous trigger-based indexing (writes land in `search_index`
// immediately, so there's nothing to track), kept out of this module
// entirely rather than adding an unused type. Intentionally omitted;
// noted here only so a future async/background indexer (e.g. once file
// *content* extraction is slow enough to defer) has an obvious note
// pointing at `search_index_metadata` (see `migrations/0001_initial_schema.sql`)
// as where that bookkeeping already lives, schema-ready and unused today.
